### ISSUE TITLE
Names for namemap

### ISSUE THREAD

**Issue by zaosociety** [among-the-fence/wiggly-draft#17]
ogre magi to jakiro
jakiro to ogre magi
broodmother to mommy
weaver to bug
luna to looona
nyx assassin to nyx nyx nyx
anti mage to auntie mage
crystal maiden to rylai
enchantress to sproink
tidehunter to thiccboy
wraith king to bone king

**Comment by doubleyuhtee** [comment]
Shit those are funny.
