### ISSUE TITLE
Add Legends tag to data cards and search results

### ISSUE THREAD

**Issue by Poddo** [among-the-fence/wiggly-draft#21]
Append an emoji or (Legends) text to datacards, maybe the text and emoji for a card and just the emoji in search results?

**Comment by iumopapisdn** [comment]
Default wargear options shown on one of the buttons for datacards

**Comment by doubleyuhtee** [comment]
https://github.com/among-the-fence/wiggly-draft/commit/926a987b65b410f87a2e557e1ee10fd061165d8f
