### ISSUE TITLE
add keywords to search (mortal wounds, deep strike, Vehicle, infantry, etc)

### ISSUE THREAD

**Issue by iumopapisdn** [among-the-fence/wiggly-draft#29]
deep strike is an actual keyworded ability so might need to be implemented slightly different, but if we could search for things that say apply mortal wounds from an ability like Squighog Boyz or Zoanthropes that would be neat.

Mortal wounds specifically gets interesting because keywords like Grenades and Vehicle give them access to grenade and tankshock strats, which i would "count" as having access to mortal wounds. Maybe include those, maybe not, dunno what would be best. probably start with just the mortal wound text itself

**Comment by doubleyuhtee** [comment]
[done](https://github.com/among-the-fence/wiggly-draft/commit/3b87f39b52ba511349ac6ebfc8837a195e9b28de)
