### ISSUE TITLE
comma separated != don't seem to work for factions. Does seem to work for other stats like movement

### ISSUE THREAD

**Issue by iumopapisdn** [among-the-fence/wiggly-draft#41]

**Comment by iumopapisdn** [comment]
oh it looks like comma separated factions dont function at all, even inclusive. so you probably knew about that

**Comment by doubleyuhtee** [comment]
https://github.com/among-the-fence/wiggly-draft/commit/41262cb8a0d56551c35bc75459e739ef404f3ade
